kind: Deployment
apiVersion: apps/v1
metadata:
 name: noderedrepo-1
spec:
 replicas: 3
 selector:
  matchLabels:
   app: noderedrepo-1
 template:
  metadata:
   labels:
    app: noderedrepo-1
  spec:
   containers:
   - name: nodered-cluster
     image: gcr.io/synapses-323217/github.com/misbahhassan08/noderedrepo-1:latest
     ports:
     - containerPort: 1880
