apiVersion: v1 
kind: Service
metadata:
 name: noderedrepo-1
spec:
 type: LoadBalancer
 selector:
  app: noderedrepo-1
 ports:
 - protocol: TCP
   port: 80
   targetPort: 1880
---
kind: Deployment
apiVersion: apps/v1
metadata:
 name: noderedrepo-1
spec:
 replicas: 1
 selector:
  matchLabels:
   app: noderedrepo-1
 template:
  metadata:
   labels:
    app: noderedrepo-1
  spec:
   containers:
   - name: cluster-1
     image: gcr.io/synapses-323217/github.com/misbahhassan08/noderedrepo-1:latest
     ports:
     - containerPort: 1880
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
 name: noderedrepo-1-ingress
 annotations:
  kubernetes.io/ingress.global-static-ip-name: noderedrepo1
  networking.gke.io/managed-certificates: noderedrepo-1-certificate
  kubernetes.io/ingress.class: "gce"
spec:
 rules:
  -host: noderedrepo1.com
   http:
    paths:
     - path: /
       backend:
        serviceName: noderedrepo-1
        servicePort: 80
---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
 name: noderedrepo-1-certificate
spec:
 domains:
  - noderedrepo1.com
