---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "nginx-3"
  namespace: "default"
  labels:
    app: "nginx-3"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "nginx-3"
  template:
    metadata:
      labels:
        app: "nginx-3"
    spec:
      containers:
      - name: "github-misbahhassan08-noderedrepo-1-1"
        image: "gcr.io/synapses-323217/github_misbahhassan08_noderedrepo-1:latest"
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "nginx-3-hpa-myto"
  namespace: "default"
  labels:
    app: "nginx-3"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "nginx-3"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80
